title:            Aleksandr Sandrovsky
description:      Machine learning and data science from a dilettant point of view.
disqus_shortname: sandrovsky
url:

owner:
  name:           Aleksandr Sandrovsky
  avatar:         avatar.png
  bio:            "Senior software engineer and newbie to machine learning"
  email:          asandrovsky@gmail.com
  github:         Sundrique
  stackexchange:  https://stackexchange.com/users/4401592/sundrique
  linkedin:       sandrovsky

google_analytics: UA-69989050-1

timezone:    Asia/Ho_Chi_Minh
future:      true
highlighter: pygments
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:year/:month/:day/:title.html

paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]